# Generated by Django 6.0.5 on 2026-05-26 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('office_phone', models.CharField(choices=[('0979661111', '0979661111'), ('0978661111', '0978661111')], default='0979661111', max_length=10)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('time', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Morning', max_length=20)),
                ('total_price', models.FloatField()),
                ('advance', models.FloatField(default=0)),
                ('extra', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('fuel', models.IntegerField(default=0)),
                ('repair', models.IntegerField(default=0)),
                ('oil', models.IntegerField(default=0)),
                ('office_rent', models.IntegerField(default=0)),
                ('house_rent', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor', models.FloatField(default=0)),
                ('packers', models.FloatField(default=0)),
                ('supervisor', models.FloatField(default=0)),
                ('driver', models.FloatField(default=0)),
                ('stairs', models.FloatField(default=0)),
                ('additional', models.FloatField(default=0)),
                ('time', models.CharField(default='', max_length=50)),
                ('derdare', models.IntegerField(default=0)),
                ('night', models.IntegerField(default=0)),
                ('long_way', models.IntegerField(default=0)),
                ('carpenter', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
