# Generated by Django 6.0.1 on 2026-05-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor', models.FloatField(default=0)),
                ('packers', models.FloatField(default=0)),
                ('driver', models.FloatField(default=0)),
                ('supervisor', models.FloatField(default=0)),
                ('additional', models.FloatField(default=0)),
                ('miscellaneous', models.FloatField(default=0)),
                ('total', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
