# Generated by Django 6.0.5 on 2026-05-13 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='jordan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='stairs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
