# Generated by Django 6.0.5 on 2026-05-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expense_booking_expense_jordan_expense_stairs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('fuel', models.IntegerField(default=0)),
                ('paints', models.IntegerField(default=0)),
                ('repair', models.IntegerField(default=0)),
                ('oil', models.IntegerField(default=0)),
                ('house_rent', models.IntegerField(default=0)),
                ('donation', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
