# Generated by Django 6.0.5 on 2026-05-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_businessrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='office_phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
