# Generated by Django 6.0.5 on 2026-05-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking_office_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='jordan',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='miscellaneous',
        ),
        migrations.AddField(
            model_name='expense',
            name='carpenter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='derdare',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='long_way',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='night',
            field=models.IntegerField(default=0),
        ),
    ]
