# Generated by Django 6.0.5 on 2026-05-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_expense_jordan_remove_expense_miscellaneous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
