# Generated by Django 6.0.5 on 2026-05-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_expense_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyexpense',
            old_name='donation',
            new_name='office_rent',
        ),
        migrations.RemoveField(
            model_name='monthlyexpense',
            name='paints',
        ),
    ]
