# Generated by Django 6.0.5 on 2026-05-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_donation_monthlyexpense_office_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='extra',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='advance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='office_phone',
            field=models.CharField(choices=[('0979661111', '0979661111'), ('0978661111', '0978661111')], default='0979661111', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
