# Generated by Django 6.0.5 on 2026-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_booking_extra_booking_time_alter_booking_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyexpense',
            name='payment',
            field=models.FloatField(default=0),
        ),
    ]
