# Generated by Django 6.0.5 on 2026-06-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessrule',
            name='description',
        ),
        migrations.RemoveField(
            model_name='businessrule',
            name='title',
        ),
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessrule',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
